from typing import Protocol, TypeVar, Generic, List, Optional

T = TypeVar("T")

class BaseRepository(Protocol, Generic[T]):
    def get(self, obj_id: int) -> Optional[T]: ...
    def list(self) -> List[T]: ...
    def create(self, entity: T) -> T: ...
    def update(self, entity: T) -> T: ...
    def delete(self, obj_id: int) -> None: ...
